- hosts: all
  vars:
    mysql_root_password: chembl
  tasks:
  - name: Install MySQL
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    become: yes
    with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
  - name: Start the MySQL service
    sudo: yes
    service: 
      name: mysql 
      state: started
      enabled: true
  - name: update mysql root password as chembl
    sudo: yes
    mysql_user: 
      name: root 
      host: "{{ item }}" 
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - 0.0.0.0
      - ::1
      - localhost 
  - name: Create chembl user
    mysql_user: user=chembl password={{mysql_root_password}} priv=*.*.ALL state=present
  - name: Create chembl_23 database
    mysql_db: db=chembl23 state=present
